### ISSUE TITLE
Wrong getting started instruction

### ISSUE THREAD

**Issue by fab7** [cloudFPGA/cFp_Zoo#7]
FYI, Step-1 tells the 'user to `git checkout main` but the branch is called `master`.

**Comment by diamantopoulos** [comment]
Nice to bring this up @fab7. However, before this step, I have this one `cd cFp_Zoo/cFDK`. This is because `cFDK`'s default branch is `main` and not `master`. However just adding `recursive` to git is enough, so I've updated it in [2abb27a](https://github.com/cloudFPGA/cFp_Zoo/commit/2abb27aa2b17413e954d33daa8f88f67cba748e6).  Thanks!

**Comment by fab7** [comment]
Thanks for the fix. The more specific the instructions, the better it is when it comes to reproduce a problem in such a large framework ;-)
